name: portfolio-optimization
channels:
  - defaults
dependencies:
  - python=3.8  # Replace with your preferred Python version
  - pandas==1.3.3
  - numpy==1.21.2
  - scipy==1.7.3
  - matplotlib==3.4.3
  - seaborn==0.11.2
  - scikit-learn==0.24.2
  - yfinance==0.1.63
